export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gray-100">
      <div className="mx-auto max-w-4xl px-8 py-16">
        <h1 className="text-5xl font-bold text-purple-700">Terms of Service</h1>

        <p className="mt-8 text-gray-700 leading-8">
          By using Pollacle, you agree to use the platform responsibly and provide accurate information when creating or supporting campaigns.
        </p>

        <p className="mt-6 text-gray-700 leading-8">
          Survey participation must be completed honestly and in accordance with the requirements of our research partners. Supporters must be at least 18 years old, and they may close a survey window at any time without penalty.
        </p>

        <p className="mt-6 text-gray-700 leading-8">
          Credits generated by supporters are subject to audit by our survey partners and may be reversed if they are deemed fraudulent, incomplete, disqualified, or otherwise in violation of partner policies. Pollacle reserves the right to review, restrict, or remove campaigns that violate platform guidelines.
        </p>

        <p className="mt-6 text-gray-700 leading-8">
          Survey-generated credits are promotional credits, not tax-deductible charitable donations. If a fundraiser receives more than $600 in a calendar year, additional tax reporting documentation may be required in accordance with applicable law.
        </p>
      </div>
    </main>
  );
}
