CREATE TABLE "User" ("id" TEXT NOT NULL, "name" TEXT, "email" TEXT, "emailVerified" TIMESTAMP(3), "image" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Account" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "type" TEXT NOT NULL, "provider" TEXT NOT NULL, "providerAccountId" TEXT NOT NULL, "refresh_token" TEXT, "access_token" TEXT, "expires_at" INTEGER, "token_type" TEXT, "scope" TEXT, "id_token" TEXT, "session_state" TEXT, CONSTRAINT "Account_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Session" ("id" TEXT NOT NULL, "sessionToken" TEXT NOT NULL, "userId" TEXT NOT NULL, "expires" TIMESTAMP(3) NOT NULL, CONSTRAINT "Session_pkey" PRIMARY KEY ("id"));
CREATE TABLE "VerificationToken" ("identifier" TEXT NOT NULL, "token" TEXT NOT NULL, "expires" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Fundraiser" ("id" TEXT NOT NULL, "userId" TEXT, "slug" TEXT NOT NULL, "title" TEXT NOT NULL, "story" TEXT NOT NULL, "category" TEXT NOT NULL, "goalAmount" DOUBLE PRECISION NOT NULL, "amountRaised" DOUBLE PRECISION NOT NULL DEFAULT 0, "surveySupporters" INTEGER NOT NULL DEFAULT 0, "cashDonations" INTEGER NOT NULL DEFAULT 0, "views" INTEGER NOT NULL DEFAULT 0, "coverImage" TEXT, "status" TEXT NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Fundraiser_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SurveyCompletion" ("id" TEXT NOT NULL, "fundraiserId" TEXT NOT NULL, "userId" TEXT, "provider" TEXT NOT NULL DEFAULT 'CPX Research', "transactionId" TEXT, "rewardAmount" DOUBLE PRECISION NOT NULL DEFAULT 0, "status" TEXT NOT NULL DEFAULT 'STARTED', "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" TIMESTAMP(3), CONSTRAINT "SurveyCompletion_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SurveySession" ("id" TEXT NOT NULL, "fundraiserId" TEXT NOT NULL, "userId" TEXT, "status" TEXT NOT NULL DEFAULT 'STARTED', "provider" TEXT NOT NULL DEFAULT 'CPX Research', "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" TIMESTAMP(3), "referrer" TEXT DEFAULT 'Direct', "utmSource" TEXT, "utmMedium" TEXT, "utmCampaign" TEXT, CONSTRAINT "SurveySession_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Consent" ("id" TEXT NOT NULL, "userId" TEXT, "email" TEXT, "purpose" TEXT NOT NULL, "value" BOOLEAN NOT NULL DEFAULT true, "ip" TEXT, "userAgent" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Consent_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "Account_provider_providerAccountId_key" ON "Account"("provider", "providerAccountId");
CREATE UNIQUE INDEX "Session_sessionToken_key" ON "Session"("sessionToken");
CREATE UNIQUE INDEX "VerificationToken_token_key" ON "VerificationToken"("token");
CREATE UNIQUE INDEX "VerificationToken_identifier_token_key" ON "VerificationToken"("identifier", "token");
CREATE UNIQUE INDEX "Fundraiser_slug_key" ON "Fundraiser"("slug");
CREATE UNIQUE INDEX "SurveyCompletion_transactionId_key" ON "SurveyCompletion"("transactionId");
ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Fundraiser" ADD CONSTRAINT "Fundraiser_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SurveyCompletion" ADD CONSTRAINT "SurveyCompletion_fundraiserId_fkey" FOREIGN KEY ("fundraiserId") REFERENCES "Fundraiser"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SurveySession" ADD CONSTRAINT "SurveySession_fundraiserId_fkey" FOREIGN KEY ("fundraiserId") REFERENCES "Fundraiser"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Consent" ADD CONSTRAINT "Consent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
